use crate::entities::tweaks::context_menu::{
    is_classic_context_menu_applied, is_copy_image_applied, is_create_symlink_applied,
    is_menu_show_delay_disabled, is_take_ownership_applied, set_classic_context_menu,
    set_copy_image, set_create_symlink, set_menu_show_delay_disabled, set_take_ownership,
};
use crate::entities::tweaks::explorer::{
    is_hide_gallery_applied, is_hide_home_applied, is_hide_linux_applied, is_hide_network_applied,
    is_open_to_this_pc_applied, is_wsl_installed, set_hide_gallery, set_hide_home, set_hide_linux,
    set_hide_network, set_open_to_this_pc,
};
use crate::entities::tweaks::input::{
    is_csrss_priority_applied, is_disable_mouse_acceleration_applied,
    is_raw_mouse_throttle_applied, set_csrss_priority, set_disable_mouse_acceleration,
    set_raw_mouse_throttle,
};
use crate::entities::tweaks::interface_tweak::{
    is_disable_jpeg_compression_applied, is_remove_shortcut_arrows_applied,
    is_remove_shortcut_suffix_applied, set_disable_jpeg_compression, set_remove_shortcut_arrows,
    set_remove_shortcut_suffix,
};
use crate::entities::tweaks::network::{
    is_bbr2_applied, is_disable_ndu_applied, is_fast_send_copy_applied,
    is_network_power_saving_disabled, is_rss_applied, set_bbr2, set_disable_ndu,
    set_fast_send_copy, set_network_power_saving_disabled, set_rss,
};
use crate::entities::tweaks::security::{
    are_security_center_notifications_disabled, is_download_warning_disabled,
    is_password_expiration_disabled, is_quick_access_history_disabled,
    is_removable_autoplay_disabled, is_startup_delay_disabled, is_uac_disabled,
    is_usb_power_saving_disabled, set_download_warning_disabled, set_password_expiration_disabled,
    set_quick_access_history_disabled, set_removable_autoplay_disabled,
    set_security_center_notifications_disabled, set_startup_delay_disabled, set_uac_disabled,
    set_usb_power_saving_disabled,
};
use crate::entities::tweaks::system::{
    is_disable_mpo_applied, is_gpu_tdr_delay_applied, set_disable_mpo, set_gpu_tdr_delay,
};

use super::types::*;

pub const ALL_TWEAKS: &[TweakDefinition] = &[
    TweakDefinition::new(
        "classic_context_menu",
        TweakCategory::ContextMenu,
        "icons/square-menu.svg",
        "tweaks.classic_context_menu_title",
        "tweaks.classic_context_menu_desc",
        is_classic_context_menu_applied,
        set_classic_context_menu,
    )
    .with_min_build(22000)
    .with_restart(RestartRequirement::Explorer)
    .with_side_effect(
        SideEffectLevel::Low,
        "tweaks.classic_context_menu_side_effect",
    ),
    TweakDefinition::new(
        "disable_menu_show_delay",
        TweakCategory::ContextMenu,
        "icons/zap.svg",
        "tweaks.disable_menu_delay_title",
        "tweaks.disable_menu_delay_desc",
        is_menu_show_delay_disabled,
        set_menu_show_delay_disabled,
    ),
    TweakDefinition::new(
        "create_symlink",
        TweakCategory::ContextMenu,
        "icons/link.svg",
        "tweaks.create_symlink_title",
        "tweaks.create_symlink_desc",
        is_create_symlink_applied,
        set_create_symlink,
    ),
    TweakDefinition::new(
        "take_ownership",
        TweakCategory::ContextMenu,
        "icons/shield-check.svg",
        "tweaks.take_ownership_title",
        "tweaks.take_ownership_desc",
        is_take_ownership_applied,
        set_take_ownership,
    )
    .with_side_effect(SideEffectLevel::Medium, "tweaks.take_ownership_side_effect"),
    TweakDefinition::new(
        "copy_image",
        TweakCategory::ContextMenu,
        "icons/copy-image.svg",
        "tweaks.copy_image_title",
        "tweaks.copy_image_desc",
        is_copy_image_applied,
        set_copy_image,
    ),
    TweakDefinition::new(
        "open_to_this_pc",
        TweakCategory::Explorer,
        "icons/monitor.svg",
        "tweaks.open_to_this_pc_title",
        "tweaks.open_to_this_pc_desc",
        is_open_to_this_pc_applied,
        set_open_to_this_pc,
    ),
    TweakDefinition::new(
        "hide_network_nav_pane",
        TweakCategory::Explorer,
        "icons/network.svg",
        "tweaks.hide_network_title",
        "tweaks.hide_network_desc",
        is_hide_network_applied,
        set_hide_network,
    ),
    TweakDefinition::new(
        "hide_home_nav_pane",
        TweakCategory::Explorer,
        "icons/house.svg",
        "tweaks.hide_home_title",
        "tweaks.hide_home_desc",
        is_hide_home_applied,
        set_hide_home,
    )
    .with_min_build(22000),
    TweakDefinition::new(
        "hide_gallery_nav_pane",
        TweakCategory::Explorer,
        "icons/images.svg",
        "tweaks.hide_gallery_title",
        "tweaks.hide_gallery_desc",
        is_hide_gallery_applied,
        set_hide_gallery,
    )
    .with_min_build(22000),
    TweakDefinition::new(
        "hide_linux_nav_pane",
        TweakCategory::Explorer,
        "icons/terminal.svg",
        "tweaks.hide_linux_title",
        "tweaks.hide_linux_desc",
        is_hide_linux_applied,
        set_hide_linux,
    )
    .with_custom_support(is_wsl_installed),
    TweakDefinition::new(
        "remove_shortcut_arrows",
        TweakCategory::Interface,
        "icons/arrow-up-right.svg",
        "tweaks.remove_shortcut_arrows_title",
        "tweaks.remove_shortcut_arrows_desc",
        is_remove_shortcut_arrows_applied,
        set_remove_shortcut_arrows,
    ),
    TweakDefinition::new(
        "remove_shortcut_suffix",
        TweakCategory::Interface,
        "icons/file-symlink.svg",
        "tweaks.remove_shortcut_suffix_title",
        "tweaks.remove_shortcut_suffix_desc",
        is_remove_shortcut_suffix_applied,
        set_remove_shortcut_suffix,
    ),
    TweakDefinition::new(
        "disable_jpeg_compression",
        TweakCategory::Interface,
        "icons/image.svg",
        "tweaks.disable_jpeg_compression_title",
        "tweaks.disable_jpeg_compression_desc",
        is_disable_jpeg_compression_applied,
        set_disable_jpeg_compression,
    ),
    TweakDefinition::new(
        "disable_mouse_acceleration",
        TweakCategory::Input,
        "icons/mouse-pointer.svg",
        "tweaks.disable_mouse_acceleration_title",
        "tweaks.disable_mouse_acceleration_desc",
        is_disable_mouse_acceleration_applied,
        set_disable_mouse_acceleration,
    ),
    TweakDefinition::new(
        "csrss_priority",
        TweakCategory::Input,
        "icons/chevrons-up.svg",
        "tweaks.csrss_priority_title",
        "tweaks.csrss_priority_desc",
        is_csrss_priority_applied,
        set_csrss_priority,
    )
    .with_restart(RestartRequirement::Reboot),
    TweakDefinition::new(
        "raw_mouse_throttle",
        TweakCategory::Input,
        "icons/mouse.svg",
        "tweaks.raw_mouse_throttle_title",
        "tweaks.raw_mouse_throttle_desc",
        is_raw_mouse_throttle_applied,
        set_raw_mouse_throttle,
    )
    .with_min_build(22000)
    .with_restart(RestartRequirement::Logoff),
    TweakDefinition::new(
        "disable_uac",
        TweakCategory::System,
        "icons/shield-off.svg",
        "tweaks.disable_uac_title",
        "tweaks.disable_uac_desc",
        is_uac_disabled,
        set_uac_disabled,
    )
    .with_restart(RestartRequirement::Reboot)
    .with_side_effect(SideEffectLevel::Low, "tweaks.disable_uac_side_effect"),
    TweakDefinition::new(
        "disable_download_warning",
        TweakCategory::System,
        "icons/file-down.svg",
        "tweaks.disable_download_warning_title",
        "tweaks.disable_download_warning_desc",
        is_download_warning_disabled,
        set_download_warning_disabled,
    )
    .with_side_effect(
        SideEffectLevel::Medium,
        "tweaks.disable_download_warning_side_effect",
    ),
    TweakDefinition::new(
        "disable_removable_autoplay",
        TweakCategory::System,
        "icons/usb.svg",
        "tweaks.disable_removable_autoplay_title",
        "tweaks.disable_removable_autoplay_desc",
        is_removable_autoplay_disabled,
        set_removable_autoplay_disabled,
    )
    .with_restart(RestartRequirement::Explorer),
    TweakDefinition::new(
        "disable_quick_access_history",
        TweakCategory::System,
        "icons/clock-arrow-down.svg",
        "tweaks.disable_quick_access_history_title",
        "tweaks.disable_quick_access_history_desc",
        is_quick_access_history_disabled,
        set_quick_access_history_disabled,
    )
    .with_restart(RestartRequirement::Explorer),
    TweakDefinition::new(
        "disable_security_center_notifications",
        TweakCategory::System,
        "icons/bell-off.svg",
        "tweaks.disable_security_center_notifications_title",
        "tweaks.disable_security_center_notifications_desc",
        are_security_center_notifications_disabled,
        set_security_center_notifications_disabled,
    )
    .with_min_build(18362)
    .with_restart(RestartRequirement::Logoff)
    .with_side_effect(
        SideEffectLevel::Medium,
        "tweaks.disable_security_center_notifications_side_effect",
    ),
    TweakDefinition::new(
        "disable_startup_delay",
        TweakCategory::System,
        "icons/rocket.svg",
        "tweaks.disable_startup_delay_title",
        "tweaks.disable_startup_delay_desc",
        is_startup_delay_disabled,
        set_startup_delay_disabled,
    )
    .with_restart(RestartRequirement::Logoff)
    .with_side_effect(
        SideEffectLevel::Low,
        "tweaks.disable_startup_delay_side_effect",
    ),
    TweakDefinition::new(
        "disable_password_expiration",
        TweakCategory::System,
        "icons/key-round.svg",
        "tweaks.disable_password_expiration_title",
        "tweaks.disable_password_expiration_desc",
        is_password_expiration_disabled,
        set_password_expiration_disabled,
    ),
    TweakDefinition::new(
        "disable_usb_power_saving",
        TweakCategory::System,
        "icons/usb.svg",
        "tweaks.disable_usb_power_saving_title",
        "tweaks.disable_usb_power_saving_desc",
        is_usb_power_saving_disabled,
        set_usb_power_saving_disabled,
    )
    .with_restart(RestartRequirement::Reboot)
    .with_side_effect(
        SideEffectLevel::Low,
        "tweaks.disable_usb_power_saving_side_effect",
    ),
    TweakDefinition::new(
        "gpu_tdr_delay",
        TweakCategory::System,
        "icons/timer.svg",
        "tweaks.gpu_tdr_delay_title",
        "tweaks.gpu_tdr_delay_desc",
        is_gpu_tdr_delay_applied,
        set_gpu_tdr_delay,
    )
    .with_restart(RestartRequirement::Reboot)
    .with_side_effect(SideEffectLevel::Low, "tweaks.gpu_tdr_delay_side_effect"),
    TweakDefinition::new(
        "disable_mpo",
        TweakCategory::System,
        "icons/monitor.svg",
        "tweaks.disable_mpo_title",
        "tweaks.disable_mpo_desc",
        is_disable_mpo_applied,
        set_disable_mpo,
    )
    .with_restart(RestartRequirement::Reboot)
    .with_side_effect(SideEffectLevel::Low, "tweaks.disable_mpo_side_effect"),
    TweakDefinition::new(
        "bbr2",
        TweakCategory::Network,
        "icons/gauge.svg",
        "tweaks.bbr2_title",
        "tweaks.bbr2_desc",
        is_bbr2_applied,
        set_bbr2,
    )
    .with_min_build(22621),
    TweakDefinition::new(
        "rss",
        TweakCategory::Network,
        "icons/cpu.svg",
        "tweaks.rss_title",
        "tweaks.rss_desc",
        is_rss_applied,
        set_rss,
    ),
    TweakDefinition::new(
        "fast_send_copy",
        TweakCategory::Network,
        "icons/zap.svg",
        "tweaks.fast_send_copy_title",
        "tweaks.fast_send_copy_desc",
        is_fast_send_copy_applied,
        set_fast_send_copy,
    )
    .with_restart(RestartRequirement::Reboot),
    TweakDefinition::new(
        "disable_ndu",
        TweakCategory::Network,
        "icons/chart-network.svg",
        "tweaks.disable_ndu_title",
        "tweaks.disable_ndu_desc",
        is_disable_ndu_applied,
        set_disable_ndu,
    )
    .with_restart(RestartRequirement::Reboot)
    .with_side_effect(SideEffectLevel::Low, "tweaks.disable_ndu_side_effect"),
    TweakDefinition::new(
        "disable_network_power_saving",
        TweakCategory::Network,
        "icons/leaf.svg",
        "tweaks.disable_network_power_saving_title",
        "tweaks.disable_network_power_saving_desc",
        is_network_power_saving_disabled,
        set_network_power_saving_disabled,
    )
    .with_restart(RestartRequirement::Reboot)
    .with_side_effect(
        SideEffectLevel::Low,
        "tweaks.disable_network_power_saving_side_effect",
    ),
];
