use crate::entities::tweaks::privacy::{
    is_activity_history_disabled, is_advertising_id_disabled, is_app_camera_mic_access_disabled,
    is_app_compat_telemetry_disabled, is_app_file_system_access_disabled,
    is_app_personal_data_access_disabled, is_ceip_sqm_disabled, is_cloud_speech_cortana_disabled,
    is_cloud_sync_disabled, is_developer_telemetry_disabled, is_feedback_notifications_disabled,
    is_input_telemetry_disabled, is_location_and_sensors_disabled,
    is_search_bing_integration_disabled, is_telemetry_and_diagnostics_disabled,
    is_website_language_access_disabled, is_wifi_sense_disabled,
    is_windows_error_reporting_disabled, set_activity_history_disabled,
    set_advertising_id_disabled, set_app_camera_mic_access_disabled,
    set_app_compat_telemetry_disabled, set_app_file_system_access_disabled,
    set_app_personal_data_access_disabled, set_ceip_sqm_disabled,
    set_cloud_speech_cortana_disabled, set_cloud_sync_disabled, set_developer_telemetry_disabled,
    set_feedback_notifications_disabled, set_input_telemetry_disabled,
    set_location_and_sensors_disabled, set_search_bing_integration_disabled,
    set_telemetry_and_diagnostics_disabled, set_website_language_access_disabled,
    set_wifi_sense_disabled, set_windows_error_reporting_disabled,
};
use crate::entities::tweaks::registry::types::{
    RestartRequirement, SideEffectLevel, TweakCategory, TweakDefinition,
};

pub const PRIVACY_TWEAKS: [TweakDefinition; 18] = [
    TweakDefinition::new(
        "telemetry_and_diagnostics",
        TweakCategory::Privacy,
        "icons/shield-off.svg",
        "tweaks.telemetry_and_diagnostics_title",
        "tweaks.telemetry_and_diagnostics_desc",
        is_telemetry_and_diagnostics_disabled,
        set_telemetry_and_diagnostics_disabled,
    )
    .with_restart(RestartRequirement::Reboot),
    TweakDefinition::new(
        "app_compat_telemetry",
        TweakCategory::Privacy,
        "icons/box.svg",
        "tweaks.app_compat_telemetry_title",
        "tweaks.app_compat_telemetry_desc",
        is_app_compat_telemetry_disabled,
        set_app_compat_telemetry_disabled,
    ),
    TweakDefinition::new(
        "ceip_sqm",
        TweakCategory::Privacy,
        "icons/chart-bar.svg",
        "tweaks.ceip_sqm_title",
        "tweaks.ceip_sqm_desc",
        is_ceip_sqm_disabled,
        set_ceip_sqm_disabled,
    ),
    TweakDefinition::new(
        "windows_error_reporting",
        TweakCategory::Privacy,
        "icons/file-exclamation-point.svg",
        "tweaks.windows_error_reporting_title",
        "tweaks.windows_error_reporting_desc",
        is_windows_error_reporting_disabled,
        set_windows_error_reporting_disabled,
    ),
    TweakDefinition::new(
        "advertising_id",
        TweakCategory::Privacy,
        "icons/sparkles.svg",
        "tweaks.advertising_id_title",
        "tweaks.advertising_id_desc",
        is_advertising_id_disabled,
        set_advertising_id_disabled,
    )
    .with_side_effect(SideEffectLevel::Low, "tweaks.advertising_id_side_effect"),
    TweakDefinition::new(
        "activity_history",
        TweakCategory::Privacy,
        "icons/clock-arrow-down.svg",
        "tweaks.activity_history_title",
        "tweaks.activity_history_desc",
        is_activity_history_disabled,
        set_activity_history_disabled,
    )
    .with_restart(RestartRequirement::Explorer),
    TweakDefinition::new(
        "input_telemetry",
        TweakCategory::Privacy,
        "icons/pen-tool.svg",
        "tweaks.input_telemetry_title",
        "tweaks.input_telemetry_desc",
        is_input_telemetry_disabled,
        set_input_telemetry_disabled,
    ),
    TweakDefinition::new(
        "cloud_speech_cortana",
        TweakCategory::Privacy,
        "icons/mic-audio-lines.svg",
        "tweaks.cloud_speech_cortana_title",
        "tweaks.cloud_speech_cortana_desc",
        is_cloud_speech_cortana_disabled,
        set_cloud_speech_cortana_disabled,
    ),
    TweakDefinition::new(
        "search_bing_integration",
        TweakCategory::Privacy,
        "icons/search.svg",
        "tweaks.search_bing_integration_title",
        "tweaks.search_bing_integration_desc",
        is_search_bing_integration_disabled,
        set_search_bing_integration_disabled,
    )
    .with_restart(RestartRequirement::Explorer),
    TweakDefinition::new(
        "cloud_sync",
        TweakCategory::Privacy,
        "icons/cloud-sync.svg",
        "tweaks.cloud_sync_title",
        "tweaks.cloud_sync_desc",
        is_cloud_sync_disabled,
        set_cloud_sync_disabled,
    )
    .with_side_effect(SideEffectLevel::Low, "tweaks.cloud_sync_side_effect"),
    TweakDefinition::new(
        "location_and_sensors",
        TweakCategory::Privacy,
        "icons/map-pin.svg",
        "tweaks.location_and_sensors_title",
        "tweaks.location_and_sensors_desc",
        is_location_and_sensors_disabled,
        set_location_and_sensors_disabled,
    )
    .with_side_effect(
        SideEffectLevel::Low,
        "tweaks.location_and_sensors_side_effect",
    ),
    TweakDefinition::new(
        "developer_telemetry",
        TweakCategory::Privacy,
        "icons/terminal.svg",
        "tweaks.developer_telemetry_title",
        "tweaks.developer_telemetry_desc",
        is_developer_telemetry_disabled,
        set_developer_telemetry_disabled,
    )
    .with_restart(RestartRequirement::Logoff),
    TweakDefinition::new(
        "feedback_notifications",
        TweakCategory::Privacy,
        "icons/message-square.svg",
        "tweaks.feedback_notifications_title",
        "tweaks.feedback_notifications_desc",
        is_feedback_notifications_disabled,
        set_feedback_notifications_disabled,
    ),
    TweakDefinition::new(
        "website_language_access",
        TweakCategory::Privacy,
        "icons/languages.svg",
        "tweaks.website_language_access_title",
        "tweaks.website_language_access_desc",
        is_website_language_access_disabled,
        set_website_language_access_disabled,
    ),
    TweakDefinition::new(
        "wifi_sense",
        TweakCategory::Privacy,
        "icons/wifi.svg",
        "tweaks.wifi_sense_title",
        "tweaks.wifi_sense_desc",
        is_wifi_sense_disabled,
        set_wifi_sense_disabled,
    ),
    TweakDefinition::new(
        "app_camera_mic_access",
        TweakCategory::Privacy,
        "icons/video.svg",
        "tweaks.app_camera_mic_access_title",
        "tweaks.app_camera_mic_access_desc",
        is_app_camera_mic_access_disabled,
        set_app_camera_mic_access_disabled,
    )
    .with_side_effect(SideEffectLevel::Medium, "tweaks.app_camera_mic_side_effect"),
    TweakDefinition::new(
        "app_personal_data_access",
        TweakCategory::Privacy,
        "icons/user-x.svg",
        "tweaks.app_personal_data_access_title",
        "tweaks.app_personal_data_access_desc",
        is_app_personal_data_access_disabled,
        set_app_personal_data_access_disabled,
    )
    .with_side_effect(SideEffectLevel::Low, "tweaks.app_personal_data_side_effect"),
    TweakDefinition::new(
        "app_file_system_access",
        TweakCategory::Privacy,
        "icons/folder-lock.svg",
        "tweaks.app_file_system_access_title",
        "tweaks.app_file_system_access_desc",
        is_app_file_system_access_disabled,
        set_app_file_system_access_disabled,
    ),
];
