use crate::features::navigation::AppRoute;

#[derive(Clone, Copy, Debug)]
pub struct DropdownTweakMeta {
    pub id: &'static str,
    pub route: AppRoute,
    pub icon: &'static str,
    pub title_key: &'static str,
    pub desc_key: &'static str,
    pub min_build: Option<u32>,
}

pub const DROPDOWN_TWEAKS: [DropdownTweakMeta; 3] = [
    DropdownTweakMeta {
        id: "keyboard_repeat",
        route: AppRoute::Input,
        icon: "icons/keyboard.svg",
        title_key: "tweaks.keyboard_repeat_title",
        desc_key: "tweaks.keyboard_repeat_desc",
        min_build: None,
    },
    DropdownTweakMeta {
        id: "ctf_optimization",
        route: AppRoute::Input,
        icon: "icons/type.svg",
        title_key: "tweaks.ctf_optimization_title",
        desc_key: "tweaks.ctf_optimization_desc",
        min_build: None,
    },
    DropdownTweakMeta {
        id: "snapkey",
        route: AppRoute::Input,
        icon: "icons/crosshair-2.svg",
        title_key: "tweaks.snapkey_title",
        desc_key: "tweaks.snapkey_desc",
        min_build: None,
    },
];

#[must_use]
pub fn get_tweak_keywords(tweak_id: &str) -> &'static [&'static str] {
    match tweak_id {
        // Dropdown input tweaks
        "snapkey" => &[
            "socd",
            "snapkey",
            "snap key",
            "snap tap",
            "snappy tappy",
            "null bind",
            "nullbind",
            "counter strafe",
            "counter strafing",
            "counter-strafe",
            "стрейф",
            "бинд",
            "контр-стрейф",
            "wasd",
            "esdf",
            "azerty",
        ],
        "ctf_optimization" => &[
            "ctf",
            "ctfmon",
            "ctfmon.exe",
            "text input",
            "input service",
            "text input management",
            "служба ввода",
            "цтф",
            "оптимизация ввода",
        ],
        "keyboard_repeat" => &[
            "keyboard",
            "repeat",
            "repeat delay",
            "repeat rate",
            "typematic",
            "filter keys",
            "задержка повтора",
            "скорость повтора",
            "клавиатура",
            "повтор",
        ],

        // Context Menu
        "classic_context_menu" => &[
            "context menu",
            "right click",
            "shift f10",
            "контекстное меню",
            "пкм",
            "меню",
            "классическое меню",
            "win10 menu",
        ],
        "disable_menu_show_delay" => &[
            "menu delay",
            "mouse hover",
            "submenus",
            "задержка меню",
            "показ подменю",
        ],
        "take_ownership" => &[
            "ownership",
            "permission",
            "access denied",
            "admin rights",
            "take own",
            "права доступа",
            "стать владельцем",
            "владелец файла",
        ],
        "copy_image" => &[
            "copy image",
            "clipboard",
            "image to clipboard",
            "буфер обмена",
            "копировать изображение",
        ],
        "create_symlink" => &[
            "symlink",
            "symbolic link",
            "junction",
            "hard link",
            "символическая ссылка",
            "ярлык",
        ],

        // Explorer
        "open_to_this_pc" => &[
            "this pc",
            "my computer",
            "этот компьютер",
            "мой компьютер",
            "проводник",
        ],
        "hide_gallery" => &["gallery", "photos", "галерея", "фотографии"],
        "hide_home" => &["home", "quick access", "главная", "быстрый доступ"],
        "hide_network" => &["network", "сеть"],
        "hide_linux" => &["linux", "wsl", "линукс", "ubuntu"],

        // Interface
        "remove_shortcut_arrows" => &[
            "shortcut arrow",
            "arrow overlay",
            "стрелки ярлыков",
            "ярлык",
            "значок ярлыка",
        ],
        "remove_shortcut_suffix" => &["shortcut suffix", "ярлык суффикс", "слово ярлык"],
        "disable_jpeg_compression" => &[
            "wallpaper",
            "jpeg quality",
            "wallpaper compression",
            "сжатие обоев",
            "качество обоев",
            "обои",
        ],

        // Input
        "disable_mouse_acceleration" => &[
            "mouse acceleration",
            "raw input",
            "enhanced pointer precision",
            "акселерация мыши",
            "ускорение мыши",
            "мышь",
        ],
        "raw_mouse_throttle" => &[
            "mouse polling",
            "high polling rate",
            "mouse lag",
            "частота опроса",
            "1000hz",
            "4000hz",
            "8000hz",
            "мышь",
        ],
        "csrss_priority" => &[
            "csrss",
            "process priority",
            "input latency",
            "realtime",
            "high priority",
            "приоритет csrss",
            "задержка ввода",
        ],

        // System
        "gpu_tdr_delay" => &[
            "tdr",
            "tdrdelay",
            "gpu timeout",
            "driver crash",
            "таймаут видеокарты",
            "вылет драйвера",
            "видеокарта",
            "видеодрайвер",
        ],
        "disable_mpo" => &[
            "mpo",
            "multiplane overlay",
            "stutter",
            "black screen",
            "мигание",
            "статтеры",
            "черный экран",
            "оверлей",
        ],

        // Network
        "bbr2" => &[
            "bbr",
            "bbr2",
            "tcp",
            "congestion control",
            "google tcp",
            "контроль перегрузки",
            "пинг",
            "сеть",
        ],
        "rss" => &[
            "rss",
            "receive side scaling",
            "multi-queue",
            "cpu cores network",
            "масштабирование приема",
        ],
        "fast_send_copy" => &[
            "fast send",
            "tcp latency",
            "быстрая отправка",
            "сеть",
            "отправка пакетов",
        ],
        "disable_ndu" => &[
            "ndu",
            "memory leak",
            "network data usage",
            "non paged pool",
            "утечка памяти",
            "утечка памяти ndu",
        ],
        "disable_network_power_saving" => &[
            "network power",
            "ethernet sleep",
            "nic power",
            "green ethernet",
            "энергосбережение сети",
            "сетевая карта",
        ],

        // Security
        "disable_usb_power_saving" => &[
            "usb sleep",
            "usb suspend",
            "usb power",
            "отключение usb",
            "питание usb",
            "порты usb",
        ],
        "disable_startup_delay" => &[
            "startup delay",
            "autostart speed",
            "fast boot",
            "задержка автозапуска",
            "быстрый запуск",
        ],
        "disable_password_expiration" => &[
            "password expiration",
            "password expire",
            "срок действия пароля",
            "пароль",
        ],
        "disable_quick_access_history" => &[
            "recent files",
            "quick access history",
            "frequent folders",
            "недавние файлы",
            "быстрый доступ",
        ],
        "disable_removable_autoplay" => &[
            "autoplay",
            "autorun",
            "usb autorun",
            "автозапуск",
            "автозапуск флешек",
        ],
        "disable_security_center_notifications" => &[
            "security notification",
            "defender toast",
            "windows defender popup",
            "уведомления безопасности",
            "защитник",
        ],
        "disable_download_warning" => &[
            "open file warning",
            "zone identifier",
            "smartscreen",
            "open file security",
            "предупреждение при открытии файла",
            "скачанные файлы",
        ],
        "disable_uac" => &[
            "uac",
            "user account control",
            "admin prompt",
            "контроль учетных записей",
            "уведомления uac",
        ],

        // Privacy
        "telemetry_and_diagnostics" => &[
            "telemetry",
            "diagnostic data",
            "diagtrack",
            "telemetry diagnostics",
            "телеметрия",
            "сбор данных",
            "диагностика",
        ],
        "app_compat_telemetry" => &[
            "app compat",
            "aitagent",
            "telemetry",
            "совместимость приложений",
        ],
        "ceip_sqm" => &[
            "ceip",
            "sqm",
            "customer experience",
            "программа улучшения ПО",
        ],
        "windows_error_reporting" => &["wer", "crash report", "error report", "отчеты об ошибках"],
        "advertising_id" => &[
            "ad id",
            "advertising id",
            "personalized ads",
            "рекламный идентификатор",
            "реклама",
        ],
        "location_and_sensors" => &[
            "location",
            "gps",
            "sensors",
            "геолокация",
            "местоположение",
            "датчики",
        ],
        "cloud_speech_cortana" => &[
            "cortana",
            "speech recognition",
            "voice typing",
            "голосовой ввод",
            "распознавание речи",
        ],
        "feedback_notifications" => &[
            "feedback",
            "feedback hub",
            "windows feedback",
            "отзывы",
            "опросы",
        ],
        "input_telemetry" => &[
            "typing telemetry",
            "ink typing",
            "keylogger telemetry",
            "рукописный ввод",
            "телеметрия ввода",
        ],
        "activity_history" => &[
            "timeline",
            "activity history",
            "user activity",
            "журнал действий",
            "хронология",
        ],
        "cloud_sync" => &[
            "cloud sync",
            "settings sync",
            "onedrive sync",
            "синхронизация настроек",
        ],
        "search_bing_integration" => &[
            "bing search",
            "web search",
            "start menu search",
            "поиск bing",
            "поиск в интернете",
        ],
        "wifi_sense" => &[
            "wifi sense",
            "hotspot share",
            "wi-fi sense",
            "контроль wi-fi",
        ],
        "app_camera_mic_access" => &[
            "camera access",
            "microphone access",
            "webcam",
            "доступ к камере",
            "микрофон",
        ],
        "app_file_system_access" => &[
            "file system access",
            "disk access",
            "доступ к файловой системе",
        ],
        "app_personal_data_access" => &[
            "contacts",
            "calendar",
            "personal data",
            "контакты",
            "календарь",
            "персональные данные",
        ],
        "website_language_access" => &[
            "language list",
            "website language",
            "языковой список сайтов",
        ],
        "developer_telemetry" => &[
            "developer telemetry",
            "vs telemetry",
            "visual studio",
            "телеметрия разработчика",
        ],

        _ => &[],
    }
}
