[package]
name = "winsentials-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
gpui.workspace = true
rust-i18n.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", branch = "main", default-features = false, features = ["test-support"] }
